language: shell

services:
  - docker

notifications:
  email: false

script:
  - sudo apt-get install python3-pip python3-setuptools python3-wheel -y
  - python3 -m pip install wheel jsonschema
  - cd tools && python3 indexing.py
  - cat index_all.json
