language: shell

services:
  - docker

notifications:
  email: false

before_install:
  - openssl aes-256-cbc -K $encrypted_3b9f0b9d36d1_key -iv $encrypted_3b9f0b9d36d1_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - ls

script:
  - sudo apt-get install python3-pip python3-setuptools python3-wheel -y
  - python3 -m pip install wheel jsonschema
  - cd tools && python3 main.py
  - cat index_all.json
