language: shell

services:
  - docker

notifications:
  email: false

before_install:
  - chmod a+x tools/before_install.sh && source tools/before_install.sh

install:
  - sudo apt-get install python3-pip python3-setuptools python3-wheel -y
  - python3 -m pip install wheel jsonschema PyEmail

script:
  - cd tools && python3 main.py || travis_terminate 1
  - docker pull summergift/csp_test:v1.0
  - cd ..
  - docker run -v "`pwd`:/rt-thread/sdk-index" -it summergift/csp_test:v1.0 bash -c "python /rt-thread/sdk-index/tools/csp_check/csp_check.py"
  - cd tools/csp_check && python3 mail_send.py
